from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import pandas as pd
from ultralytics import YOLO

from two_phase_utils import (
    box_iou,
    ensure_dir,
    extract_yolo_boxes,
    filter_weapon_boxes,
    load_split_manifest,
    load_two_phase_config,
    parse_voc_xml,
    project_root,
    resolve_path,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate single-stage and two-phase weapon detections.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--split", choices=["train", "val", "test"], help="Named split manifest to evaluate.")
    group.add_argument("--manifest", type=Path, help="Explicit manifest CSV with image_path and annotation_path.")
    parser.add_argument("--config", type=Path, default=None, help="Path to configs/two_phase.yaml.")
    parser.add_argument("--two-phase-predictions", type=Path, default=None, help="CSV generated by run_two_phase_inference.py.")
    parser.add_argument(
        "--two-phase-image-summary",
        type=Path,
        default=None,
        help="Optional per-image summary CSV from run_two_phase_inference.py.",
    )
    parser.add_argument("--single-stage-predictions", type=Path, default=None, help="Existing single-stage predictions CSV.")
    parser.add_argument(
        "--single-stage-model",
        type=Path,
        default=None,
        help="Weapon detector checkpoint used to generate single-stage predictions if no CSV is provided.",
    )
    parser.add_argument("--device", default=None, help="Inference device, for example cpu, 0, or cuda:0.")
    parser.add_argument("--max-images", type=int, default=None, help="Optional cap for smoke tests.")
    parser.add_argument("--output-prefix", default=None, help="Optional prefix for saved evaluation outputs.")
    return parser.parse_args()


def resolve_manifest(args: argparse.Namespace, root: Path) -> tuple[str, pd.DataFrame]:
    if args.split:
        return args.split, load_split_manifest(root, args.split)

    manifest_path = args.manifest
    if manifest_path is None:
        raise ValueError("Expected --split or --manifest.")
    if not manifest_path.is_absolute():
        manifest_path = root / manifest_path
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing manifest file: {manifest_path}")
    return manifest_path.stem, pd.read_csv(manifest_path)


def resolve_optional_path(root: Path, path: Path | None) -> Path | None:
    if path is None:
        return None
    if path.is_absolute():
        return path
    return root / path


def generate_single_stage_predictions(
    manifest_df: pd.DataFrame,
    model_path: Path,
    output_path: Path,
    device: str,
    conf_threshold: float,
    iou_threshold: float,
) -> pd.DataFrame:
    if not model_path.exists():
        raise FileNotFoundError(
            f"Missing single-stage weapon checkpoint: {model_path}. "
            "Pass --single-stage-model with the Sprint 3 YOLO26n best.pt path."
        )

    root = project_root()
    model = YOLO(str(model_path))
    rows: list[dict[str, object]] = []
    for _, row in manifest_df.iterrows():
        image_path = root / Path(row["image_path"])
        result = model.predict(
            source=str(image_path),
            conf=conf_threshold,
            iou=iou_threshold,
            verbose=False,
            device=device,
        )[0]
        for pred_idx, box in enumerate(extract_yolo_boxes(result)):
            rows.append(
                {
                    "image_stem": row["image_stem"],
                    "image_path": row["image_path"],
                    "prediction_index": pred_idx,
                    "weapon_confidence": round(float(box["confidence"]), 6),
                    "xmin": round(float(box["xmin"]), 3),
                    "ymin": round(float(box["ymin"]), 3),
                    "xmax": round(float(box["xmax"]), 3),
                    "ymax": round(float(box["ymax"]), 3),
                }
            )
    df = pd.DataFrame(
        rows,
        columns=[
            "image_stem",
            "image_path",
            "prediction_index",
            "weapon_confidence",
            "xmin",
            "ymin",
            "xmax",
            "ymax",
        ],
    )
    df.to_csv(output_path, index=False)
    return df


def evaluate_predictions(
    manifest_df: pd.DataFrame,
    predictions_df: pd.DataFrame,
    iou_threshold: float,
) -> tuple[dict[str, float], pd.DataFrame]:
    preds_by_image: dict[str, list[dict[str, float]]] = defaultdict(list)
    for _, row in predictions_df.iterrows():
        preds_by_image[str(row["image_path"])].append(
            {
                "confidence": float(row["weapon_confidence"]),
                "xmin": float(row["xmin"]),
                "ymin": float(row["ymin"]),
                "xmax": float(row["xmax"]),
                "ymax": float(row["ymax"]),
            }
        )

    totals = {"tp": 0, "fp": 0, "fn": 0}
    per_image_rows: list[dict[str, object]] = []

    for _, row in manifest_df.iterrows():
        annotation_path = project_root() / Path(row["annotation_path"])
        _, _, objects = parse_voc_xml(annotation_path)
        gt_boxes = filter_weapon_boxes(objects)
        preds = sorted(preds_by_image.get(str(row["image_path"]), []), key=lambda item: item["confidence"], reverse=True)

        matched_gt: set[int] = set()
        tp = 0
        fp = 0
        for pred in preds:
            best_iou = 0.0
            best_gt_idx = None
            for gt_idx, gt_box in enumerate(gt_boxes):
                if gt_idx in matched_gt:
                    continue
                current_iou = box_iou(pred, gt_box)
                if current_iou > best_iou:
                    best_iou = current_iou
                    best_gt_idx = gt_idx
            if best_gt_idx is not None and best_iou >= iou_threshold:
                matched_gt.add(best_gt_idx)
                tp += 1
            else:
                fp += 1

        fn = len(gt_boxes) - len(matched_gt)
        totals["tp"] += tp
        totals["fp"] += fp
        totals["fn"] += fn
        per_image_rows.append(
            {
                "image_stem": row["image_stem"],
                "image_path": row["image_path"],
                "ground_truth_boxes": len(gt_boxes),
                "predicted_boxes": len(preds),
                "tp": tp,
                "fp": fp,
                "fn": fn,
            }
        )

    precision = totals["tp"] / (totals["tp"] + totals["fp"]) if (totals["tp"] + totals["fp"]) > 0 else 0.0
    recall = totals["tp"] / (totals["tp"] + totals["fn"]) if (totals["tp"] + totals["fn"]) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    detections_per_image = len(predictions_df) / max(1, len(manifest_df))

    metrics = {
        "tp": totals["tp"],
        "fp": totals["fp"],
        "fn": totals["fn"],
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "detections_per_image": detections_per_image,
    }
    return metrics, pd.DataFrame(per_image_rows)


def maybe_load_image_summary(image_summary_path: Path | None) -> dict[str, float]:
    if image_summary_path is None or not image_summary_path.exists():
        return {}
    df = pd.read_csv(image_summary_path)
    return {
        "stage0_miss_count": int(df["stage0_image_miss"].sum()) if "stage0_image_miss" in df.columns else "",
        "stage1_rejected": int(df["persons_filtered_out"].sum()) if "persons_filtered_out" in df.columns else "",
        "stage2_passed": int(df["persons_passed_stage2"].sum()) if "persons_passed_stage2" in df.columns else "",
    }


def main() -> None:
    args = parse_args()
    root = project_root()
    config = load_two_phase_config(args.config)
    split_name, manifest_df = resolve_manifest(args, root)
    if args.max_images is not None:
        manifest_df = manifest_df.head(args.max_images).copy()

    device = args.device or config["inference"]["default_device"]
    evaluation_dir = resolve_path(root, config["paths"]["evaluation_dir"])
    ensure_dir(evaluation_dir)
    output_prefix = args.output_prefix or split_name

    single_stage_predictions_path = resolve_optional_path(root, args.single_stage_predictions)
    two_phase_predictions_path = resolve_optional_path(root, args.two_phase_predictions)
    two_phase_image_summary_path = resolve_optional_path(root, args.two_phase_image_summary)
    single_stage_model_path = resolve_optional_path(root, args.single_stage_model)

    if single_stage_predictions_path is None:
        if single_stage_model_path is None:
            single_stage_model_path = resolve_path(root, config["models"]["weapon_detector"])
        single_stage_predictions_path = evaluation_dir / f"{output_prefix}_single_stage_predictions.csv"
        single_stage_predictions_df = generate_single_stage_predictions(
            manifest_df=manifest_df,
            model_path=single_stage_model_path,
            output_path=single_stage_predictions_path,
            device=device,
            conf_threshold=float(config["thresholds"]["weapon_conf"]),
            iou_threshold=float(config["thresholds"]["weapon_iou"]),
        )
    else:
        if not single_stage_predictions_path.exists():
            raise FileNotFoundError(f"Missing single-stage predictions CSV: {single_stage_predictions_path}")
        single_stage_predictions_df = pd.read_csv(single_stage_predictions_path)

    comparison_rows: list[dict[str, object]] = []
    per_image_outputs: dict[str, pd.DataFrame] = {}

    single_stage_metrics, single_stage_per_image = evaluate_predictions(
        manifest_df,
        single_stage_predictions_df,
        iou_threshold=float(config["thresholds"]["evaluation_iou"]),
    )
    comparison_rows.append(
        {
            "pipeline": "single_stage",
            **single_stage_metrics,
            "stage0_miss_count": "",
            "stage1_rejected": "",
            "stage2_passed": "",
        }
    )
    per_image_outputs["single_stage"] = single_stage_per_image

    if two_phase_predictions_path is not None:
        if not two_phase_predictions_path.exists():
            raise FileNotFoundError(f"Missing two-phase predictions CSV: {two_phase_predictions_path}")
        two_phase_predictions_df = pd.read_csv(two_phase_predictions_path)
        two_phase_metrics, two_phase_per_image = evaluate_predictions(
            manifest_df,
            two_phase_predictions_df,
            iou_threshold=float(config["thresholds"]["evaluation_iou"]),
        )
        extra_stats = maybe_load_image_summary(two_phase_image_summary_path)
        comparison_rows.append({"pipeline": "two_phase", **two_phase_metrics, **extra_stats})
        per_image_outputs["two_phase"] = two_phase_per_image

        comparison_rows.append(
            {
                "pipeline": "delta_two_phase_minus_single_stage",
                "tp": two_phase_metrics["tp"] - single_stage_metrics["tp"],
                "fp": two_phase_metrics["fp"] - single_stage_metrics["fp"],
                "fn": two_phase_metrics["fn"] - single_stage_metrics["fn"],
                "precision": two_phase_metrics["precision"] - single_stage_metrics["precision"],
                "recall": two_phase_metrics["recall"] - single_stage_metrics["recall"],
                "f1": two_phase_metrics["f1"] - single_stage_metrics["f1"],
                "detections_per_image": two_phase_metrics["detections_per_image"] - single_stage_metrics["detections_per_image"],
                "stage0_miss_count": extra_stats.get("stage0_miss_count", ""),
                "stage1_rejected": extra_stats.get("stage1_rejected", ""),
                "stage2_passed": extra_stats.get("stage2_passed", ""),
            }
        )

    comparison_df = pd.DataFrame(comparison_rows)
    comparison_path = evaluation_dir / f"{output_prefix}_comparison.csv"
    summary_path = evaluation_dir / f"{output_prefix}_summary.md"
    comparison_df.to_csv(comparison_path, index=False)

    for pipeline_name, df in per_image_outputs.items():
        df.to_csv(evaluation_dir / f"{output_prefix}_{pipeline_name}_per_image.csv", index=False)

    with summary_path.open("w", encoding="utf-8") as f:
        f.write("# Detection Pipeline Evaluation Summary\n\n")
        f.write(f"- Split: `{split_name}`\n")
        f.write(f"- Evaluation IoU threshold: `{float(config['thresholds']['evaluation_iou']):.2f}`\n\n")
        f.write("## Comparison\n\n")
        f.write(comparison_df.to_markdown(index=False))
        f.write("\n")

    print(f"[OK] Saved comparison CSV: {comparison_path}")
    print(f"[OK] Saved summary: {summary_path}")


if __name__ == "__main__":
    main()
