from __future__ import annotations

import argparse
import os
from collections import defaultdict
from pathlib import Path

import pandas as pd
from pandas.errors import EmptyDataError

PROJECT_ROOT = Path(__file__).resolve().parent.parent
os.environ.setdefault("YOLO_CONFIG_DIR", str(PROJECT_ROOT))

from ultralytics import YOLO

from two_phase_utils import (
    box_iou,
    center_of_box,
    crop_matches_weapon,
    ensure_dir,
    extract_yolo_boxes,
    filter_weapon_boxes,
    load_split_manifest,
    load_two_phase_config,
    parse_voc_xml,
    point_in_box,
    project_root,
    resolve_path,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate single-stage and two-phase weapon detections.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--split", choices=["train", "val", "test"], help="Named split manifest to evaluate.")
    group.add_argument("--manifest", type=Path, help="Explicit manifest CSV with image_path and annotation_path.")
    parser.add_argument("--config", type=Path, default=None, help="Path to configs/two_phase.yaml.")
    parser.add_argument("--two-phase-predictions", type=Path, default=None, help="CSV generated by run_two_phase_inference.py.")
    parser.add_argument(
        "--two-phase-image-summary",
        type=Path,
        default=None,
        help="Optional per-image summary CSV from run_two_phase_inference.py.",
    )
    parser.add_argument("--single-stage-predictions", type=Path, default=None, help="Existing single-stage predictions CSV.")
    parser.add_argument(
        "--single-stage-model",
        type=Path,
        default=None,
        help="Weapon detector checkpoint used to generate single-stage predictions if no CSV is provided.",
    )
    parser.add_argument("--device", default=None, help="Inference device, for example cpu, 0, or cuda:0.")
    parser.add_argument("--max-images", type=int, default=None, help="Optional cap for smoke tests.")
    parser.add_argument("--output-prefix", default=None, help="Optional prefix for saved evaluation outputs.")
    return parser.parse_args()


def resolve_manifest(args: argparse.Namespace, root: Path) -> tuple[str, pd.DataFrame]:
    if args.split:
        return args.split, load_split_manifest(root, args.split)

    manifest_path = args.manifest
    if manifest_path is None:
        raise ValueError("Expected --split or --manifest.")
    if not manifest_path.is_absolute():
        manifest_path = root / manifest_path
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing manifest file: {manifest_path}")
    return manifest_path.stem, pd.read_csv(manifest_path)


def resolve_optional_path(root: Path, path: Path | None) -> Path | None:
    if path is None:
        return None
    if path.is_absolute():
        return path
    return root / path


def infer_two_phase_debug_path(predictions_path: Path | None, suffix: str) -> Path | None:
    if predictions_path is None:
        return None
    stem = predictions_path.stem
    if stem.endswith("_predictions"):
        prefix = stem[: -len("_predictions")]
        return predictions_path.with_name(f"{prefix}_{suffix}.csv")
    return predictions_path.with_name(f"{stem}_{suffix}.csv")


def read_csv_if_present(path: Path | None) -> pd.DataFrame | None:
    if path is None or not path.exists():
        return None
    try:
        return pd.read_csv(path)
    except EmptyDataError:
        return None


def generate_single_stage_predictions(
    manifest_df: pd.DataFrame,
    model_path: Path,
    output_path: Path,
    device: str,
    conf_threshold: float,
    iou_threshold: float,
) -> pd.DataFrame:
    if not model_path.exists():
        raise FileNotFoundError(
            f"Missing single-stage weapon checkpoint: {model_path}. "
            "Pass --single-stage-model with the Sprint 3 YOLO26n best.pt path."
        )

    root = project_root()
    model = YOLO(str(model_path))
    rows: list[dict[str, object]] = []
    for _, row in manifest_df.iterrows():
        image_path = root / Path(row["image_path"])
        result = model.predict(
            source=str(image_path),
            conf=conf_threshold,
            iou=iou_threshold,
            verbose=False,
            device=device,
        )[0]
        for pred_idx, box in enumerate(extract_yolo_boxes(result)):
            rows.append(
                {
                    "image_stem": row["image_stem"],
                    "image_path": row["image_path"],
                    "prediction_index": pred_idx,
                    "weapon_confidence": round(float(box["confidence"]), 6),
                    "xmin": round(float(box["xmin"]), 3),
                    "ymin": round(float(box["ymin"]), 3),
                    "xmax": round(float(box["xmax"]), 3),
                    "ymax": round(float(box["ymax"]), 3),
                }
            )
    df = pd.DataFrame(
        rows,
        columns=[
            "image_stem",
            "image_path",
            "prediction_index",
            "weapon_confidence",
            "xmin",
            "ymin",
            "xmax",
            "ymax",
        ],
    )
    df.to_csv(output_path, index=False)
    return df


def group_prediction_rows(predictions_df: pd.DataFrame) -> dict[str, list[dict[str, float]]]:
    preds_by_image: dict[str, list[dict[str, float]]] = defaultdict(list)
    for _, row in predictions_df.iterrows():
        preds_by_image[str(row["image_path"])].append(
            {
                "confidence": float(row["weapon_confidence"]),
                "xmin": float(row["xmin"]),
                "ymin": float(row["ymin"]),
                "xmax": float(row["xmax"]),
                "ymax": float(row["ymax"]),
            }
        )
    return preds_by_image


def evaluate_predictions(
    manifest_df: pd.DataFrame,
    predictions_df: pd.DataFrame,
    iou_threshold: float,
) -> tuple[dict[str, float], pd.DataFrame]:
    preds_by_image = group_prediction_rows(predictions_df)

    totals = {"tp": 0, "fp": 0, "fn": 0}
    per_image_rows: list[dict[str, object]] = []

    for _, row in manifest_df.iterrows():
        annotation_path = project_root() / Path(row["annotation_path"])
        _, _, objects = parse_voc_xml(annotation_path)
        gt_boxes = filter_weapon_boxes(objects)
        preds = sorted(preds_by_image.get(str(row["image_path"]), []), key=lambda item: item["confidence"], reverse=True)

        matched_gt: set[int] = set()
        tp = 0
        fp = 0
        for pred in preds:
            best_iou = 0.0
            best_gt_idx = None
            for gt_idx, gt_box in enumerate(gt_boxes):
                if gt_idx in matched_gt:
                    continue
                current_iou = box_iou(pred, gt_box)
                if current_iou > best_iou:
                    best_iou = current_iou
                    best_gt_idx = gt_idx
            if best_gt_idx is not None and best_iou >= iou_threshold:
                matched_gt.add(best_gt_idx)
                tp += 1
            else:
                fp += 1

        fn = len(gt_boxes) - len(matched_gt)
        totals["tp"] += tp
        totals["fp"] += fp
        totals["fn"] += fn
        per_image_rows.append(
            {
                "image_stem": row["image_stem"],
                "image_path": row["image_path"],
                "ground_truth_boxes": len(gt_boxes),
                "predicted_boxes": len(preds),
                "tp": tp,
                "fp": fp,
                "fn": fn,
            }
        )

    precision = totals["tp"] / (totals["tp"] + totals["fp"]) if (totals["tp"] + totals["fp"]) > 0 else 0.0
    recall = totals["tp"] / (totals["tp"] + totals["fn"]) if (totals["tp"] + totals["fn"]) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    detections_per_image = len(predictions_df) / max(1, len(manifest_df))

    metrics = {
        "tp": totals["tp"],
        "fp": totals["fp"],
        "fn": totals["fn"],
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "detections_per_image": detections_per_image,
    }
    return metrics, pd.DataFrame(per_image_rows)


def maybe_load_image_summary(image_summary_path: Path | None) -> dict[str, float]:
    if image_summary_path is None or not image_summary_path.exists():
        return {}
    df = pd.read_csv(image_summary_path)
    return {
        "stage0_miss_count": int(df["stage0_image_miss"].sum()) if "stage0_image_miss" in df.columns else "",
        "stage0_raw_person_miss_count": int(df["stage0_raw_person_miss"].sum()) if "stage0_raw_person_miss" in df.columns else "",
        "stage1_rejected": int(df["persons_filtered_out"].sum()) if "persons_filtered_out" in df.columns else "",
        "stage2_passed": int(df["persons_passed_stage2"].sum()) if "persons_passed_stage2" in df.columns else "",
        "raw_person_cover": int(df["raw_person_cover"].sum()) if "raw_person_cover" in df.columns else "",
        "expanded_crop_cover": int(df["expanded_crop_cover"].sum()) if "expanded_crop_cover" in df.columns else "",
        "detections_removed_by_nms": int(df["final_weapon_detections_removed_by_nms"].sum())
        if "final_weapon_detections_removed_by_nms" in df.columns
        else "",
    }


def compute_two_phase_error_breakdown(
    manifest_df: pd.DataFrame,
    final_predictions_df: pd.DataFrame,
    pre_nms_predictions_df: pd.DataFrame | None,
    candidate_df: pd.DataFrame | None,
    iou_threshold: float,
    match_ioa_threshold: float,
) -> tuple[dict[str, int], pd.DataFrame]:
    final_by_image = group_prediction_rows(final_predictions_df)
    pre_nms_by_image = group_prediction_rows(pre_nms_predictions_df) if pre_nms_predictions_df is not None else {}
    candidate_by_image: dict[str, list[dict[str, object]]] = defaultdict(list)
    if candidate_df is not None:
        for _, row in candidate_df.iterrows():
            candidate_by_image[str(row["image_path"])].append(row.to_dict())

    totals = {
        "missed_by_person_detector": 0,
        "missed_by_crop_cover": 0,
        "missed_by_crop_detector": 0,
        "removed_by_final_nms": 0,
    }
    per_image_rows: list[dict[str, object]] = []

    for _, row in manifest_df.iterrows():
        annotation_path = project_root() / Path(row["annotation_path"])
        _, _, objects = parse_voc_xml(annotation_path)
        gt_boxes = filter_weapon_boxes(objects)
        final_preds = final_by_image.get(str(row["image_path"]), [])
        pre_nms_preds = pre_nms_by_image.get(str(row["image_path"]), [])
        candidates = candidate_by_image.get(str(row["image_path"]), [])

        image_counts = {
            "missed_by_person_detector": 0,
            "missed_by_crop_cover": 0,
            "missed_by_crop_detector": 0,
            "removed_by_final_nms": 0,
        }

        for gt_box in gt_boxes:
            final_match = any(box_iou(pred, gt_box) >= iou_threshold for pred in final_preds)
            if final_match:
                continue

            raw_cover = False
            expanded_cover = False
            for candidate in candidates:
                person_box = {
                    "xmin": float(candidate["person_xmin"]),
                    "ymin": float(candidate["person_ymin"]),
                    "xmax": float(candidate["person_xmax"]),
                    "ymax": float(candidate["person_ymax"]),
                }
                crop_box = {
                    "xmin": float(candidate["crop_xmin"]),
                    "ymin": float(candidate["crop_ymin"]),
                    "xmax": float(candidate["crop_xmax"]),
                    "ymax": float(candidate["crop_ymax"]),
                }
                center_x, center_y = center_of_box(gt_box)
                if point_in_box(center_x, center_y, person_box):
                    raw_cover = True
                if crop_matches_weapon(crop_box, gt_box, match_ioa_threshold=match_ioa_threshold)[0]:
                    expanded_cover = True
                if raw_cover and expanded_cover:
                    break

            pre_nms_match = any(box_iou(pred, gt_box) >= iou_threshold for pred in pre_nms_preds)
            if not raw_cover:
                image_counts["missed_by_person_detector"] += 1
            elif not expanded_cover:
                image_counts["missed_by_crop_cover"] += 1
            elif pre_nms_match:
                image_counts["removed_by_final_nms"] += 1
            else:
                image_counts["missed_by_crop_detector"] += 1

        for key in totals:
            totals[key] += image_counts[key]

        per_image_rows.append(
            {
                "image_stem": row["image_stem"],
                "image_path": row["image_path"],
                **image_counts,
            }
        )

    return totals, pd.DataFrame(per_image_rows)


def main() -> None:
    args = parse_args()
    root = project_root()
    config = load_two_phase_config(args.config)
    split_name, manifest_df = resolve_manifest(args, root)
    if args.max_images is not None:
        manifest_df = manifest_df.head(args.max_images).copy()

    device = args.device or config["inference"]["default_device"]
    evaluation_dir = resolve_path(root, config["paths"]["evaluation_dir"])
    ensure_dir(evaluation_dir)
    output_prefix = args.output_prefix or split_name

    single_stage_predictions_path = resolve_optional_path(root, args.single_stage_predictions)
    two_phase_predictions_path = resolve_optional_path(root, args.two_phase_predictions)
    two_phase_image_summary_path = resolve_optional_path(root, args.two_phase_image_summary)
    single_stage_model_path = resolve_optional_path(root, args.single_stage_model)

    if single_stage_predictions_path is None:
        if single_stage_model_path is None:
            single_stage_model_path = resolve_path(root, config["models"]["weapon_detector"])
        single_stage_predictions_path = evaluation_dir / f"{output_prefix}_single_stage_predictions.csv"
        single_stage_predictions_df = generate_single_stage_predictions(
            manifest_df=manifest_df,
            model_path=single_stage_model_path,
            output_path=single_stage_predictions_path,
            device=device,
            conf_threshold=float(config["thresholds"]["weapon_conf"]),
            iou_threshold=float(config["thresholds"]["weapon_iou"]),
        )
    else:
        if not single_stage_predictions_path.exists():
            raise FileNotFoundError(f"Missing single-stage predictions CSV: {single_stage_predictions_path}")
        single_stage_predictions_df = pd.read_csv(single_stage_predictions_path)

    comparison_rows: list[dict[str, object]] = []
    per_image_outputs: dict[str, pd.DataFrame] = {}

    single_stage_metrics, single_stage_per_image = evaluate_predictions(
        manifest_df,
        single_stage_predictions_df,
        iou_threshold=float(config["thresholds"]["evaluation_iou"]),
    )
    comparison_rows.append(
        {
            "pipeline": "single_stage",
            **single_stage_metrics,
            "stage0_miss_count": "",
            "stage0_raw_person_miss_count": "",
            "stage1_rejected": "",
            "stage2_passed": "",
            "raw_person_cover": "",
            "expanded_crop_cover": "",
            "detections_removed_by_nms": "",
            "missed_by_person_detector": "",
            "missed_by_crop_cover": "",
            "missed_by_crop_detector": "",
            "removed_by_final_nms": "",
        }
    )
    per_image_outputs["single_stage"] = single_stage_per_image

    if two_phase_predictions_path is not None:
        if not two_phase_predictions_path.exists():
            raise FileNotFoundError(f"Missing two-phase predictions CSV: {two_phase_predictions_path}")
        two_phase_predictions_df = pd.read_csv(two_phase_predictions_path)
        two_phase_metrics, two_phase_per_image = evaluate_predictions(
            manifest_df,
            two_phase_predictions_df,
            iou_threshold=float(config["thresholds"]["evaluation_iou"]),
        )
        extra_stats = maybe_load_image_summary(two_phase_image_summary_path)

        pre_nms_predictions_path = infer_two_phase_debug_path(two_phase_predictions_path, "predictions_pre_nms")
        person_candidates_path = infer_two_phase_debug_path(two_phase_predictions_path, "person_candidates")
        pre_nms_predictions_df = read_csv_if_present(pre_nms_predictions_path)
        person_candidates_df = read_csv_if_present(person_candidates_path)
        error_breakdown, breakdown_per_image = compute_two_phase_error_breakdown(
            manifest_df=manifest_df,
            final_predictions_df=two_phase_predictions_df,
            pre_nms_predictions_df=pre_nms_predictions_df,
            candidate_df=person_candidates_df,
            iou_threshold=float(config["thresholds"]["evaluation_iou"]),
            match_ioa_threshold=float(config["dataset"].get("match_ioa_threshold", 0.60)),
        )

        comparison_rows.append({"pipeline": "two_phase", **two_phase_metrics, **extra_stats, **error_breakdown})
        per_image_outputs["two_phase"] = two_phase_per_image
        per_image_outputs["two_phase_error_breakdown"] = breakdown_per_image

        comparison_rows.append(
            {
                "pipeline": "delta_two_phase_minus_single_stage",
                "tp": two_phase_metrics["tp"] - single_stage_metrics["tp"],
                "fp": two_phase_metrics["fp"] - single_stage_metrics["fp"],
                "fn": two_phase_metrics["fn"] - single_stage_metrics["fn"],
                "precision": two_phase_metrics["precision"] - single_stage_metrics["precision"],
                "recall": two_phase_metrics["recall"] - single_stage_metrics["recall"],
                "f1": two_phase_metrics["f1"] - single_stage_metrics["f1"],
                "detections_per_image": two_phase_metrics["detections_per_image"] - single_stage_metrics["detections_per_image"],
                "stage0_miss_count": extra_stats.get("stage0_miss_count", ""),
                "stage0_raw_person_miss_count": extra_stats.get("stage0_raw_person_miss_count", ""),
                "stage1_rejected": extra_stats.get("stage1_rejected", ""),
                "stage2_passed": extra_stats.get("stage2_passed", ""),
                "raw_person_cover": extra_stats.get("raw_person_cover", ""),
                "expanded_crop_cover": extra_stats.get("expanded_crop_cover", ""),
                "detections_removed_by_nms": extra_stats.get("detections_removed_by_nms", ""),
                "missed_by_person_detector": error_breakdown.get("missed_by_person_detector", ""),
                "missed_by_crop_cover": error_breakdown.get("missed_by_crop_cover", ""),
                "missed_by_crop_detector": error_breakdown.get("missed_by_crop_detector", ""),
                "removed_by_final_nms": error_breakdown.get("removed_by_final_nms", ""),
            }
        )

    comparison_df = pd.DataFrame(comparison_rows)
    comparison_path = evaluation_dir / f"{output_prefix}_comparison.csv"
    summary_path = evaluation_dir / f"{output_prefix}_summary.md"
    comparison_df.to_csv(comparison_path, index=False)

    for pipeline_name, df in per_image_outputs.items():
        df.to_csv(evaluation_dir / f"{output_prefix}_{pipeline_name}_per_image.csv", index=False)

    with summary_path.open("w", encoding="utf-8") as f:
        f.write("# Detection Pipeline Evaluation Summary\n\n")
        f.write(f"- Split: `{split_name}`\n")
        f.write(f"- Evaluation IoU threshold: `{float(config['thresholds']['evaluation_iou']):.2f}`\n\n")
        f.write("## Comparison\n\n")
        f.write(comparison_df.to_markdown(index=False))
        f.write("\n")
        if "two_phase" in per_image_outputs:
            f.write("\n## Two-Phase Error Breakdown\n\n")
            f.write("- `missed_by_person_detector`: no detected person box covered the weapon center.\n")
            f.write("- `missed_by_crop_cover`: a person proposal existed, but the expanded crop still did not cover the weapon well enough.\n")
            f.write("- `missed_by_crop_detector`: the crop covered the weapon, but Stage 2 still missed it.\n")
            f.write("- `removed_by_final_nms`: a pre-NMS crop detection matched the weapon, but it was suppressed by image-level NMS.\n")

    print(f"[OK] Saved comparison CSV: {comparison_path}")
    print(f"[OK] Saved summary: {summary_path}")


if __name__ == "__main__":
    main()
